import { mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const USERNAME = 'donatoalvarezdev';
const API_URL = `https://www.credly.com/users/${USERNAME}/badges.json`;

const rootDir = fileURLToPath(new URL('..', import.meta.url));
const badgesDir = join(rootDir, 'public', 'badges');
const dataFilePath = join(rootDir, 'src', 'data', 'badges.ts');

async function syncBadges() {
  console.log(`Fetching badges from ${API_URL}...`);
  const response = await fetch(API_URL, {
    headers: {
      Accept: 'application/json',
      'User-Agent': 'DonatoAlvarez-Portfolio-Sync/1.0',
    },
  });

  if (!response.ok) {
    throw new Error(
      `Failed to fetch Credly badges: ${response.status} ${response.statusText}`,
    );
  }

  const json = await response.json();
  const rawBadges = Array.isArray(json?.data) ? json.data : [];
  console.log(`Found ${rawBadges.length} badges from Credly.`);

  await mkdir(badgesDir, { recursive: true });

  const badges = [];

  for (const item of rawBadges) {
    const id = item.id;
    const title = item.badge_template?.name || 'Certification';
    const issuer =
      item.badge_template?.issuer?.entities?.[0]?.entity?.name ||
      item.issuer?.summary ||
      'Credly';
    const credlyUrl = `https://www.credly.com/badges/${id}`;
    const remoteImageUrl = item.image_url || item.badge_template?.image_url;
    const issuedDate = item.issued_at_date || '';

    const localFileName = `${id}.png`;
    const localFilePath = join(badgesDir, localFileName);
    const publicImagePath = `/badges/${localFileName}`;

    if (remoteImageUrl) {
      if (!existsSync(localFilePath)) {
        console.log(`Downloading badge image for "${title}"...`);
        const imgRes = await fetch(remoteImageUrl);
        if (imgRes.ok) {
          const buffer = Buffer.from(await imgRes.arrayBuffer());
          await writeFile(localFilePath, buffer);
        } else {
          console.warn(
            `Failed to download image from ${remoteImageUrl}: ${imgRes.status}`,
          );
        }
      }
    }

    badges.push({
      id,
      title,
      issuer,
      image: publicImagePath,
      url: credlyUrl,
      issuedDate,
    });
  }

  // Format string literal to match Prettier quote style
  const formatValue = (str) => {
    const s = String(str);
    if (s.includes("'") && !s.includes('"')) {
      return `"${s}"`;
    }
    return `'${s.replace(/'/g, "\\'")}'`;
  };

  // Format the output TypeScript file with quotes matching Prettier
  const formattedItems = badges
    .map(
      (b) => `  {
    id: ${formatValue(b.id)},
    title: ${formatValue(b.title)},
    issuer: ${formatValue(b.issuer)},
    image: ${formatValue(b.image)},
    url: ${formatValue(b.url)},
    issuedDate: ${formatValue(b.issuedDate)},
  },`,
    )
    .join('\n');

  const tsContent = `// Auto-generated by scripts/sync-badges.mjs — do not edit manually.
export interface Badge {
  id: string;
  title: string;
  issuer: string;
  image: string;
  url: string;
  issuedDate: string;
}

export const badges: Badge[] = [
${formattedItems}
];
`;

  await writeFile(dataFilePath, tsContent, 'utf8');
  console.log(`Successfully synced ${badges.length} badges to ${dataFilePath}`);
}

syncBadges().catch((err) => {
  console.error('Badge sync failed:', err);
  process.exit(1);
});
