// Auto-generated by scripts/sync-badges.mjs — do not edit manually.
export interface Badge {
  id: string;
  title: string;
  issuer: string;
  image: string;
  url: string;
  issuedDate: string;
}

export const badges: Badge[] = [
  {
    id: '1878bd2c-2f09-45e6-a81a-3056ff259402',
    title: 'Google AI Essentials',
    issuer: 'Coursera',
    image: '/badges/1878bd2c-2f09-45e6-a81a-3056ff259402.png',
    url: 'https://www.credly.com/badges/1878bd2c-2f09-45e6-a81a-3056ff259402',
    issuedDate: '2026-08-22',
  },
  {
    id: 'ac1f4d5c-d5fb-493f-a6b6-42c45b44dbc6',
    title: 'MongoDB Overview: Core Concepts and Architecture',
    issuer: 'MongoDB',
    image: '/badges/ac1f4d5c-d5fb-493f-a6b6-42c45b44dbc6.png',
    url: 'https://www.credly.com/badges/ac1f4d5c-d5fb-493f-a6b6-42c45b44dbc6',
    issuedDate: '2026-09-17',
  },
  {
    id: 'dce3bb43-a7c2-463d-b10a-5723f15b3b81',
    title: 'Cloud Computing Core',
    issuer: 'edX',
    image: '/badges/dce3bb43-a7c2-463d-b10a-5723f15b3b81.png',
    url: 'https://www.credly.com/badges/dce3bb43-a7c2-463d-b10a-5723f15b3b81',
    issuedDate: '2024-10-21',
  },
  {
    id: '839f7dd2-83f3-4427-a389-4c6169e62914',
    title: 'Cybersecurity Essentials',
    issuer: 'Cisco',
    image: '/badges/839f7dd2-83f3-4427-a389-4c6169e62914.png',
    url: 'https://www.credly.com/badges/839f7dd2-83f3-4427-a389-4c6169e62914',
    issuedDate: '2021-04-14',
  },
  {
    id: '76cd4557-8db4-40c8-9052-4d8292ec11a0',
    title: 'Google AI Essentials V1',
    issuer: 'Coursera',
    image: '/badges/76cd4557-8db4-40c8-9052-4d8292ec11a0.png',
    url: 'https://www.credly.com/badges/76cd4557-8db4-40c8-9052-4d8292ec11a0',
    issuedDate: '2024-09-29',
  },
  {
    id: '7a99899f-895b-46cf-8b11-c8b4d2f92091',
    title: 'Enterprise Apps with React',
    issuer: "O'Reilly Media",
    image: '/badges/7a99899f-895b-46cf-8b11-c8b4d2f92091.png',
    url: 'https://www.credly.com/badges/7a99899f-895b-46cf-8b11-c8b4d2f92091',
    issuedDate: '2025-06-16',
  },
  {
    id: 'b19a74cd-fcb9-4212-975b-5ebd190ab498',
    title: 'CCNA 200-301 V1.1 Crash Course',
    issuer: "O'Reilly Media",
    image: '/badges/b19a74cd-fcb9-4212-975b-5ebd190ab498.png',
    url: 'https://www.credly.com/badges/b19a74cd-fcb9-4212-975b-5ebd190ab498',
    issuedDate: '2024-09-17',
  },
  {
    id: 'b196d366-8719-4ff8-84b5-7d8bcae2af7c',
    title: 'Linux Troubleshooting',
    issuer: "O'Reilly Media",
    image: '/badges/b196d366-8719-4ff8-84b5-7d8bcae2af7c.png',
    url: 'https://www.credly.com/badges/b196d366-8719-4ff8-84b5-7d8bcae2af7c',
    issuedDate: '2025-06-10',
  },
  {
    id: 'cc0c961d-8bf6-4a15-858c-25efb35ef99e',
    title: 'Microservices Bootcamp',
    issuer: "O'Reilly Media",
    image: '/badges/cc0c961d-8bf6-4a15-858c-25efb35ef99e.png',
    url: 'https://www.credly.com/badges/cc0c961d-8bf6-4a15-858c-25efb35ef99e',
    issuedDate: '2024-08-16',
  },
];
